// Code generated by go-swagger; DO NOT EDIT.

package build_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCurrentVcsInstancesObsoleteParams creates a new GetCurrentVcsInstancesObsoleteParams object
// with the default values initialized.
func NewGetCurrentVcsInstancesObsoleteParams() *GetCurrentVcsInstancesObsoleteParams {
	var ()
	return &GetCurrentVcsInstancesObsoleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCurrentVcsInstancesObsoleteParamsWithTimeout creates a new GetCurrentVcsInstancesObsoleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCurrentVcsInstancesObsoleteParamsWithTimeout(timeout time.Duration) *GetCurrentVcsInstancesObsoleteParams {
	var ()
	return &GetCurrentVcsInstancesObsoleteParams{

		timeout: timeout,
	}
}

// NewGetCurrentVcsInstancesObsoleteParamsWithContext creates a new GetCurrentVcsInstancesObsoleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCurrentVcsInstancesObsoleteParamsWithContext(ctx context.Context) *GetCurrentVcsInstancesObsoleteParams {
	var ()
	return &GetCurrentVcsInstancesObsoleteParams{

		Context: ctx,
	}
}

// NewGetCurrentVcsInstancesObsoleteParamsWithHTTPClient creates a new GetCurrentVcsInstancesObsoleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCurrentVcsInstancesObsoleteParamsWithHTTPClient(client *http.Client) *GetCurrentVcsInstancesObsoleteParams {
	var ()
	return &GetCurrentVcsInstancesObsoleteParams{
		HTTPClient: client,
	}
}

/*GetCurrentVcsInstancesObsoleteParams contains all the parameters to send to the API endpoint
for the get current vcs instances obsolete operation typically these are written to a http.Request
*/
type GetCurrentVcsInstancesObsoleteParams struct {

	/*BtLocator*/
	BtLocator string
	/*Fields*/
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get current vcs instances obsolete params
func (o *GetCurrentVcsInstancesObsoleteParams) WithTimeout(timeout time.Duration) *GetCurrentVcsInstancesObsoleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get current vcs instances obsolete params
func (o *GetCurrentVcsInstancesObsoleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get current vcs instances obsolete params
func (o *GetCurrentVcsInstancesObsoleteParams) WithContext(ctx context.Context) *GetCurrentVcsInstancesObsoleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get current vcs instances obsolete params
func (o *GetCurrentVcsInstancesObsoleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get current vcs instances obsolete params
func (o *GetCurrentVcsInstancesObsoleteParams) WithHTTPClient(client *http.Client) *GetCurrentVcsInstancesObsoleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get current vcs instances obsolete params
func (o *GetCurrentVcsInstancesObsoleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBtLocator adds the btLocator to the get current vcs instances obsolete params
func (o *GetCurrentVcsInstancesObsoleteParams) WithBtLocator(btLocator string) *GetCurrentVcsInstancesObsoleteParams {
	o.SetBtLocator(btLocator)
	return o
}

// SetBtLocator adds the btLocator to the get current vcs instances obsolete params
func (o *GetCurrentVcsInstancesObsoleteParams) SetBtLocator(btLocator string) {
	o.BtLocator = btLocator
}

// WithFields adds the fields to the get current vcs instances obsolete params
func (o *GetCurrentVcsInstancesObsoleteParams) WithFields(fields *string) *GetCurrentVcsInstancesObsoleteParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get current vcs instances obsolete params
func (o *GetCurrentVcsInstancesObsoleteParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *GetCurrentVcsInstancesObsoleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param btLocator
	if err := r.SetPathParam("btLocator", o.BtLocator); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
