// Code generated by go-swagger; DO NOT EDIT.

package build_queue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/glassechidna/go-teamcityapi/models"
)

// NewSetBuildQueuePositionParams creates a new SetBuildQueuePositionParams object
// with the default values initialized.
func NewSetBuildQueuePositionParams() *SetBuildQueuePositionParams {
	var ()
	return &SetBuildQueuePositionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetBuildQueuePositionParamsWithTimeout creates a new SetBuildQueuePositionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetBuildQueuePositionParamsWithTimeout(timeout time.Duration) *SetBuildQueuePositionParams {
	var ()
	return &SetBuildQueuePositionParams{

		timeout: timeout,
	}
}

// NewSetBuildQueuePositionParamsWithContext creates a new SetBuildQueuePositionParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetBuildQueuePositionParamsWithContext(ctx context.Context) *SetBuildQueuePositionParams {
	var ()
	return &SetBuildQueuePositionParams{

		Context: ctx,
	}
}

// NewSetBuildQueuePositionParamsWithHTTPClient creates a new SetBuildQueuePositionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetBuildQueuePositionParamsWithHTTPClient(client *http.Client) *SetBuildQueuePositionParams {
	var ()
	return &SetBuildQueuePositionParams{
		HTTPClient: client,
	}
}

/*SetBuildQueuePositionParams contains all the parameters to send to the API endpoint
for the set build queue position operation typically these are written to a http.Request
*/
type SetBuildQueuePositionParams struct {

	/*Body*/
	Body *models.Build
	/*Fields*/
	Fields *string
	/*QueuePosition*/
	QueuePosition string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set build queue position params
func (o *SetBuildQueuePositionParams) WithTimeout(timeout time.Duration) *SetBuildQueuePositionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set build queue position params
func (o *SetBuildQueuePositionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set build queue position params
func (o *SetBuildQueuePositionParams) WithContext(ctx context.Context) *SetBuildQueuePositionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set build queue position params
func (o *SetBuildQueuePositionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set build queue position params
func (o *SetBuildQueuePositionParams) WithHTTPClient(client *http.Client) *SetBuildQueuePositionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set build queue position params
func (o *SetBuildQueuePositionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the set build queue position params
func (o *SetBuildQueuePositionParams) WithBody(body *models.Build) *SetBuildQueuePositionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set build queue position params
func (o *SetBuildQueuePositionParams) SetBody(body *models.Build) {
	o.Body = body
}

// WithFields adds the fields to the set build queue position params
func (o *SetBuildQueuePositionParams) WithFields(fields *string) *SetBuildQueuePositionParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the set build queue position params
func (o *SetBuildQueuePositionParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithQueuePosition adds the queuePosition to the set build queue position params
func (o *SetBuildQueuePositionParams) WithQueuePosition(queuePosition string) *SetBuildQueuePositionParams {
	o.SetQueuePosition(queuePosition)
	return o
}

// SetQueuePosition adds the queuePosition to the set build queue position params
func (o *SetBuildQueuePositionParams) SetQueuePosition(queuePosition string) {
	o.QueuePosition = queuePosition
}

// WriteToRequest writes these params to a swagger request
func (o *SetBuildQueuePositionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param queuePosition
	if err := r.SetPathParam("queuePosition", o.QueuePosition); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
