// Code generated by go-swagger; DO NOT EDIT.

package debug

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCachedBuildPromotionsParams creates a new GetCachedBuildPromotionsParams object
// with the default values initialized.
func NewGetCachedBuildPromotionsParams() *GetCachedBuildPromotionsParams {
	var ()
	return &GetCachedBuildPromotionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCachedBuildPromotionsParamsWithTimeout creates a new GetCachedBuildPromotionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCachedBuildPromotionsParamsWithTimeout(timeout time.Duration) *GetCachedBuildPromotionsParams {
	var ()
	return &GetCachedBuildPromotionsParams{

		timeout: timeout,
	}
}

// NewGetCachedBuildPromotionsParamsWithContext creates a new GetCachedBuildPromotionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCachedBuildPromotionsParamsWithContext(ctx context.Context) *GetCachedBuildPromotionsParams {
	var ()
	return &GetCachedBuildPromotionsParams{

		Context: ctx,
	}
}

// NewGetCachedBuildPromotionsParamsWithHTTPClient creates a new GetCachedBuildPromotionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCachedBuildPromotionsParamsWithHTTPClient(client *http.Client) *GetCachedBuildPromotionsParams {
	var ()
	return &GetCachedBuildPromotionsParams{
		HTTPClient: client,
	}
}

/*GetCachedBuildPromotionsParams contains all the parameters to send to the API endpoint
for the get cached build promotions operation typically these are written to a http.Request
*/
type GetCachedBuildPromotionsParams struct {

	/*BuildTypeLocator*/
	BuildTypeLocator *string
	/*Fields*/
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get cached build promotions params
func (o *GetCachedBuildPromotionsParams) WithTimeout(timeout time.Duration) *GetCachedBuildPromotionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cached build promotions params
func (o *GetCachedBuildPromotionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cached build promotions params
func (o *GetCachedBuildPromotionsParams) WithContext(ctx context.Context) *GetCachedBuildPromotionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cached build promotions params
func (o *GetCachedBuildPromotionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cached build promotions params
func (o *GetCachedBuildPromotionsParams) WithHTTPClient(client *http.Client) *GetCachedBuildPromotionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cached build promotions params
func (o *GetCachedBuildPromotionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBuildTypeLocator adds the buildTypeLocator to the get cached build promotions params
func (o *GetCachedBuildPromotionsParams) WithBuildTypeLocator(buildTypeLocator *string) *GetCachedBuildPromotionsParams {
	o.SetBuildTypeLocator(buildTypeLocator)
	return o
}

// SetBuildTypeLocator adds the buildTypeLocator to the get cached build promotions params
func (o *GetCachedBuildPromotionsParams) SetBuildTypeLocator(buildTypeLocator *string) {
	o.BuildTypeLocator = buildTypeLocator
}

// WithFields adds the fields to the get cached build promotions params
func (o *GetCachedBuildPromotionsParams) WithFields(fields *string) *GetCachedBuildPromotionsParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get cached build promotions params
func (o *GetCachedBuildPromotionsParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *GetCachedBuildPromotionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.BuildTypeLocator != nil {

		// query param buildTypeLocator
		var qrBuildTypeLocator string
		if o.BuildTypeLocator != nil {
			qrBuildTypeLocator = *o.BuildTypeLocator
		}
		qBuildTypeLocator := qrBuildTypeLocator
		if qBuildTypeLocator != "" {
			if err := r.SetQueryParam("buildTypeLocator", qBuildTypeLocator); err != nil {
				return err
			}
		}

	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
