// Code generated by go-swagger; DO NOT EDIT.

package debug

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/glassechidna/go-teamcityapi/models"
)

// GetCachedBuildPromotionsReader is a Reader for the GetCachedBuildPromotions structure.
type GetCachedBuildPromotionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCachedBuildPromotionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCachedBuildPromotionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCachedBuildPromotionsOK creates a GetCachedBuildPromotionsOK with default headers values
func NewGetCachedBuildPromotionsOK() *GetCachedBuildPromotionsOK {
	return &GetCachedBuildPromotionsOK{}
}

/*GetCachedBuildPromotionsOK handles this case with default header values.

successful operation
*/
type GetCachedBuildPromotionsOK struct {
	Payload *models.Builds
}

func (o *GetCachedBuildPromotionsOK) Error() string {
	return fmt.Sprintf("[GET /app/rest/debug/caches/buildPromotions/content][%d] getCachedBuildPromotionsOK  %+v", 200, o.Payload)
}

func (o *GetCachedBuildPromotionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Builds)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
