// Code generated by go-swagger; DO NOT EDIT.

package agent

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/glassechidna/go-teamcityapi/models"
)

// GetAllowedRunConfigurationsReader is a Reader for the GetAllowedRunConfigurations structure.
type GetAllowedRunConfigurationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllowedRunConfigurationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllowedRunConfigurationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAllowedRunConfigurationsOK creates a GetAllowedRunConfigurationsOK with default headers values
func NewGetAllowedRunConfigurationsOK() *GetAllowedRunConfigurationsOK {
	return &GetAllowedRunConfigurationsOK{}
}

/*GetAllowedRunConfigurationsOK handles this case with default header values.

successful operation
*/
type GetAllowedRunConfigurationsOK struct {
	Payload *models.CompatibilityPolicy
}

func (o *GetAllowedRunConfigurationsOK) Error() string {
	return fmt.Sprintf("[GET /app/rest/agents/{agentLocator}/compatibilityPolicy][%d] getAllowedRunConfigurationsOK  %+v", 200, o.Payload)
}

func (o *GetAllowedRunConfigurationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CompatibilityPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
